---
title: "CS109: Introduction to Probability for Computer Scientists"
subtitle: "Section 6: Samples"
author: "Olivia Beyer Bruvik"
date: "Winter 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section 6: Samples {.tabset}

## Beta distribution
Beta(a, b):

- a: # sucesses + 1
- b: # successes + 1

## CLT
$X_i: IID$: <br>
$\sum X_i = N(n \mu, n \sigma^2$ <br>
$E[X_i] = \mu$ and $Var[X_i] = \sigma^2$

## Sampling
1. Population
  + Mean: $\mu = \frac{\sum X_i}{N}$
  + Variance: $\sigma^2 = \frac{\sum (X_i-\mu)^2}{N}$
2. Sample
  + Mean: $x = \frac{\sum X_i}{n}$
  + Variance: $S^2 = \frac{\sum (X_i-\mu)^2}{n-1}$

Unbiased: $E[S^2] = \sigma^2$

## Bootstrapping
1. Pop1
  + \mu_1
  + Var_1
2. Pop2
  + \mu_2
  + Var_2


## Problem 3: CLT {.tabset}
### Problem
Karel the dog eats an unpredictable amount of food. Every day, the dog is equally likely to
eat between a continuous amount in the range 100 to 300 grams. How much Karel eats is
independent of all other days. You only have 6.5kg of food for the next 30 days. What is the
probability that 6.5kg will be enough for the next 30 days?

### Solution
\[
\begin{aligned}
X \sim Uni(100, 300) \\
E[X_i] = 200, n = 30, Var = 3333 \\
Y \sim N(30 \times 200, 30 \times 3333) \\
P(X < 6500) = stats.norm.pdf(6500, 6000, 3333)
\end{aligned}
\]

## Problem 4: Bootstrapping {.tabset}
### Problem
A colleague has collected samples of heights of corgis that live on two different islands. The
colleague collects 50 samples from both islands.

The colleague notes that the sample mean is the same between the two groups: both are around
10 inches. However, island B has a sample variance that is 3 in2 greater than island A. The
colleague wants to make a scientific claim that corgis on island A have a significantly higher
spread of heights than corgis on island B. You are skeptical. It is possible that heights are
identically distributed across both islands and that the observed difference in variance was a
result of chance and a small sample size, i.e. the null hypothesis.
Here is the data. Each number is the height, in inches, of an independently sampled corgi (along
with the sample variance):

Island A Corgi Heights (ð‘†2 = 6.0):
13, 12, 7, 16, 9, 11, 7, 10, 9, 8, 9, 7, 16, 7, 9, 8, 13, 10, 11, 9, 13, 13, 10, 10, 9, 7, 7, 6, 7, 8, 12, 13, 9, 6, 9, 11, 10, 8, 12, 10, 9, 10, 8, 14, 13, 13, 10, 11, 12, 9

Island B Corgi Heights (ð‘†2 = 9.1):
8, 8, 16, 16, 9, 13, 14, 13, 10, 12, 10, 6, 14, 8, 13, 14, 7, 13, 7, 8, 4, 11, 7, 12, 8, 9, 12, 8, 11, 10, 12, 6, 10, 15, 11, 12, 3, 8, 11, 10, 10, 8, 12, 8, 11, 6, 7, 10, 8, 5

Warmup: You would like to put error bars around your estimate, based off this sample, that
the mean height is 10 inches for Island A Corgis. You use Standard Error of the Mean for
error bars. Standard Error makes the size of the error bars equal to the standard deviation
of your sample estimate. What is the size of your error bar?

Calculate the probability of the null hypothesis, that variance is the same across islands,
using bootstrapping.

### Solution 
Error bar (A) = $\sqrt{6.0}$ <br>
Error bar (B) = $\sqrt{9.1}$  <br>

Null hypothesis: observed difference is by random chance.

$P(h_0) = \frac{count}{10000}$, $p-value \approx 0.12 > 0.05$ 